services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${practice_root_password}
      MYSQL_DATABASE: ${practice_db}
      MYSQL_USER: ${practice_user}
      MYSQL_PASSWORD: ${practice_password}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    networks:
    - practice_network   

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ${practice_user}
      PMA_PASSWORD: ${practice_password}
    ports:
      - "8081:80"
    depends_on:
      - mysql
    networks:
      - practice_network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: practice_app
    volumes:
      - ./:/var/www/html:rw
    working_dir: /var/www/html
    depends_on:
      - mysql
    networks:
      - practice_network


volumes:
  db_data:

networks:
  practice_network:  


    